version: "3.9"

networks:
  tracker:

volumes:
  tracker-pg:

services:
  db:
    container_name: tracker-db
    image: postgres:15.3-alpine
    environment:
      POSTGRES_PASSWORD: dev
    ports:
      - "8091:5432"
    volumes:
      - "tracker-pg:/var/lib/postgresql/data"
    networks:
      - tracker
    restart: always

  app:
    container_name: tracker-app
    build: .
    ports:
      - "8090:8080"
    env_file:
      - .env
    networks:
      - tracker
    depends_on:
      - db
    restart: always
